# Generated by Django 2.2.8 on 2019-12-11 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('cd_manutencao', models.AutoField(primary_key=True, serialize=False)),
                ('dt_manutencao', models.DateField()),
                ('dt_final', models.DateField()),
                ('ds_solucao', models.TextField()),
                ('nm_funcionario', models.TextField()),
                ('cd_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.Pedido')),
            ],
        ),
    ]
