# Generated by Django 2.2.8 on 2019-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='ds_solucao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='dt_final',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='dt_manutencao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='nm_funcionario',
            field=models.TextField(null=True),
        ),
    ]
