# Generated by Django 2.2.8 on 2019-12-11 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cd_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('dt_pedido', models.DateField()),
                ('hr_pedido', models.TimeField()),
                ('nm_solicitante', models.CharField(max_length=120)),
                ('ds_problema', models.TextField()),
                ('ic_processo', models.IntegerField()),
                ('cd_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipamento.Equipamento')),
            ],
        ),
    ]
