# Generated by Django 2.2.8 on 2019-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dt_pedido',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hr_pedido',
            field=models.TimeField(auto_now=True),
        ),
    ]
