# Generated by Django 2.2.8 on 2019-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_auto_20191211_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ds_problema',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nm_solicitante',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
