from django.db import models

# Create your models here.
class Equipamento(models.Model):
	cd_equipamento = models.AutoField(primary_key=True)
	ds_equipamento = models.CharField(max_length=100, null=True)
	cd_patrimonio  = models.CharField(max_length=50, null=True)
	nm_modelo      = models.CharField(max_length=30, null=True)
	nm_fabricante  = models.CharField(max_length=20, null=True)
	nm_marca       = models.CharField(max_length=20, null=True)
	nm_setor       = models.CharField(max_length=20, null=True)
	nm_sala        = models.CharField(max_length=15, null=True)
	ic_posse       = models.CharField(max_length=10, null=True)
	cd_fiscal      = models.CharField(max_length=20, null=True)
	vl_equipamento = models.FloatField(null=True)
	dt_instalacao  = models.DateField(null=True)
	dt_garantia    = models.DateField(null=True)
	ic_manutencao  = models.CharField(max_length=5, null=True)
	cd_prestador   = models.CharField(max_length=20, null=True)
	ic_tensao      = models.FloatField(null=True)
	vl_potencia    = models.FloatField(null=True)
	ic_operacao    = models.CharField(max_length=5, null=True)
	ic_tecnico     = models.CharField(max_length=5, null=True)
	ds_insumo      = models.CharField(max_length=100, null=True)
	ds_obs         = models.TextField(null=True)
	ic_delete      = models.IntegerField(default=0, null=True)