# Generated by Django 2.2.8 on 2019-12-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('cd_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('ds_equipamento', models.CharField(max_length=100)),
                ('cd_patrimonio', models.CharField(max_length=50)),
                ('nm_modelo', models.CharField(max_length=30)),
                ('nm_fabricante', models.CharField(max_length=20)),
                ('nm_marca', models.CharField(max_length=20)),
                ('nm_setor', models.CharField(max_length=20)),
                ('nm_sala', models.CharField(max_length=15)),
                ('ic_posse', models.CharField(max_length=10)),
                ('cd_fiscal', models.CharField(max_length=20)),
                ('vl_equipamento', models.FloatField()),
                ('dt_instalacao', models.DateField()),
                ('dt_garantia', models.DateField()),
                ('ic_manutencao', models.CharField(max_length=5)),
                ('cd_prestador', models.CharField(max_length=20)),
                ('ic_tensao', models.CharField(max_length=15)),
                ('vl_potencia', models.FloatField()),
                ('ic_operacao', models.CharField(max_length=5)),
                ('ic_tecnico', models.CharField(max_length=5)),
                ('ds_insumo', models.CharField(max_length=100)),
                ('ds_obs', models.TextField()),
                ('ic_delete', models.IntegerField()),
            ],
        ),
    ]
