# Generated by Django 2.2.8 on 2019-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='cd_fiscal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='cd_prestador',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ds_insumo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ds_obs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ic_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ic_manutencao',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ic_operacao',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ic_posse',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ic_tecnico',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ic_tensao',
            field=models.FloatField(),
        ),
    ]
