# Generated by Django 2.2.8 on 2019-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamento', '0002_auto_20191211_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='cd_patrimonio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ds_equipamento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='dt_garantia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='dt_instalacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ic_delete',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ic_tensao',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nm_fabricante',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nm_marca',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nm_modelo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nm_sala',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nm_setor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='vl_equipamento',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='vl_potencia',
            field=models.FloatField(null=True),
        ),
    ]
